default_model:
  model_name: ep-20241225102429-22vn4
  base_url: https://ark.cn-beijing.volces.com/api/v3
  api_key: xxx

# manager:
#   model_name: ep-20241225203916-mvf77
#   base_url: https://ark.cn-beijing.volces.com/api/v3
#   api_key: xxx

  